{% set name = "tyssue" %}
{% set version = "0.6.2" %}
{% set sha256 = "0ee4e17ca2624ad4252a9bdd81f7e1a5ca774c807381a46ccc940c4da7e466e7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  - fn: pybind11-2.4.3.tar.gz
    url: https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz
    folder: pybind11
    sha256: 1eed57bc6863190e35637290f97a20c81cfe4d9090ac0a24f3bbf08f265eb71d
  - url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-5.0/CGAL-5.0-library.tar.xz
    folder: CGAL
    sha256: 66853a040703f8dccabba25d44c004cdcb9ea0ffff28c33b89fbfa319d795e31

build:
  number: 1
  skip: True  # [py2k or py35]

requirements:
  build:
    - cmake
    - eigen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost-cpp
    - mpfr
  host:
    - python
    - setuptools
    - pip
  run:
    - boost-cpp
    - mpfr
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPLv3.0
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
