{% set name = "tyssue" %}
{% set version = "0.6.7" %}
{% set sha256 = "a2dd1a494ba4a63f8e47107d6fa3d1dea01d8413b37ee2523b5b5462b2210fc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/DamCB/tyssue/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
build:
  number: 2
  script:
    - set "CMAKE_GENERATOR=NMake Makefiles"  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps -vv --install-option=\"--exclude-arch\""
  skip: true  # [py2k or py35]
  skip: true # [win and vc<14

requirements:
  build:
    - cmake
    - eigen
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - boost-cpp
    - mpfr
    - cgal-cpp
    - pybind11
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - jupyter
    - notebook
    - quantities
    - ipyvolume
test:
  imports:
    - tyssue
    - tyssue.behaviors
    - tyssue.config
    - tyssue.core
    - tyssue.collisions
    - tyssue.draw
    - tyssue.dynamics
    - tyssue.geometry
    - tyssue.generation
    - tyssue.io
    - tyssue.particles
    - tyssue.solvers
    - tyssue.stores
    - tyssue.topology
    - tyssue.utils

about:
  home: https://github.com/DamCB/tyssue
  license: GPLv3.0
  license_file: LICENSE
  summary: 'A tissue simulation library'
  description: |
    tyssue provides data structures and algorithms to model epithelium
    in 2D and 3D for python 3.6+
  doc_url: http://tyssue.readthedocs.io
  dev_url: https://github.com/DamCB/tyssue
extra:
  recipe-maintainers:
    - glyg
