travis:
  secure:
    BINSTAR_TOKEN: nOYoW3UsIuOasKRlP+Y96pHfZO4uHSKBD4rhv7nuSWElvb9vB98tPFnFJYmDlDntQEMcLDlk0SA0suJfdkYnlOwCFFH2Y+Zf/LD3mumWxPEDeK9tEhu3rQhYUDkzPVOHgLZ2d5j+EX/h9AJtOtTVISRdKbEY3Lo5MKDEkQi1UDmCD5DlpmoW82XaW3cYGjsicH8Ec7HvILNMsSfDzMcJND9YrLKUckpAqY5QM4LLkrDXd0RrcHdThPH3AyW0V5PBqV3ipvW6hRLKkI7dVRIh3vII5BVpPFpM+lbzNF+1yBEzX/x4FwdlOlDk8z0fMndCPmxWq7JSrgAF+fs1E9TCu5BBXHZ0sbiNy3aus8KylwgGrpx8WfwXw+JmFxFJQol2ExvF0l6pAerMWDbA3AzaC1qXpxDE0iyKWHM372Tk7QFNcRIIr/Bvxo2AugDv4riy+lzqvbGVXa7MDR+AeGCTW/MsH3Aww0VXZzWv7TrwlCVWiAH+msnN78wOWW9ctf/4Kp5rWpnJAapILTxJZYx8UXwBHyJFKBXdvU4gDM7+bsn25Gnj17orWZSlWf5iW8kAJfIpUM5QJVy5MTdtuKDpUAAEGI/I0ZT/HHfxlogbwD8tpDJCpAhzj6BVMik3oWaDd1i3HfCU+McSbiBqAIurGU8NPQC2t5ic2pPiTKcvDQA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
