travis:
  secure:
    BINSTAR_TOKEN: uu+4bgiIHveIN9Kfakt9fweJNZurCPsLlB9SG3gOubpSv2xYBetFvEJZL4Du9SJ32LaUytfffU7Bcq3+zECJv4JdHm9wK9qiB3ELCXaQ/Ja1HP9P/vKSjTE8rAFd+Mw850a2jnVkyniAhu3v9PHeMhXNGEv5mB8mXjo/rdNCG+b3cuH/I2/bFvXN/Xw1Uem1Ez/j31fK4WSxtx3sOdL0+qQ5orFFXMvlIWD0WYtJpU8d1EZ8zda6+eU3zlkMJYywIiUqkmjGdUYxXL9B4HYJt7GOPXMleF+i4F4YaxYMZXk7P7rAyUBv3HWDRdw/9Qw+QUi/qk5hed2em7XVUwOalrXgfQ54HOtohNtcyuDdj8ouidHXsZEih+eqRUL42o7ESfsm+4CyXfrsdQ8tnvPOSqQA2bwdjftmVBbYV5a7NnFZUMSueNF9JwfaZSquKuNfHY6yCN6L+zGELmq0w3ZxS158PYByVySLZos3A5pruTuvsiCmpVgLGuBOjxNx0uxzIU5Goc9D0IFhARIY7psEsk3H8RdTRXhyezzjsHnkDTp2zAwzS+YmdkY6/jSuApkwRx8zf3R8ZlYDssIr4kogjNmQsskxuKdxlILYOJFpqnvLuSVNIRSIXwRCHRunbU3ks1G5sj7p7yvu8W4/oYqaYkGIv8DBNSVgmNgca/qJJaQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
